In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [2]:
cash_book_path = 'C:\\Users\\SQL\\Documents\\BOKOPT_GL_CB_202311291624.csv'
cash_book = pd.read_csv(cash_book_path)
cash_book

,DOCKEY,DOCNO,DOCTYPE,DOCDATE,POSTDATE,TAXDATE,DESCRIPTION,DESCRIPTION2,PAYMENTMETHOD,AREA,...,LOCALDOCAMT,FROMDOCTYPE,BOUNCEDDATE,GLTRANSID,CANCELLED,DEPOSITKEY,UPDATECOUNT,PRINTCOUNT,ATTACHMENTS,NOTE
0,320,PV-1311/001,PV,2013-11-30,2013-11-30,2013-11-30,NG KOK LIANG,Payment For SSM Registration and Printing,301-001,----,...,3209.00,NaN,NaN,167,F,NaN,NaN,0,NaN,NaN
1,322,PV-1311/002,PV,2013-11-20,2013-11-20,2013-11-20,OLIVER LEE FU ONN,Payment For Nov'13 Staff Salary,301-001,----,...,3270.25,NaN,NaN,168,F,NaN,NaN,0,NaN,NaN
2,328,PV-1311/003,PV,2013-11-30,2013-11-30,2013-11-30,KUMPULAN WANG SIMPANAN PEKERJA,Payment For Nov'13 Staff EPF Contribution,301-001,----,...,480.00,NaN,NaN,169,F,NaN,NaN,0,NaN,NaN
3,330,PV-1311/004,PV,2013-11-30,2013-11-30,2013-11-30,PERTUBUHAN KESELAMATAN SOSIAL,Payment For Nov'13 Staff Socso,301-001,----,...,43.90,NaN,NaN,170,F,NaN,NaN,0,NaN,NaN
4,332,PV-1312/001,PV,2013-12-31,2013-12-31,2013-12-31,KUMPULAN WANG SIMPANAN PEKERJA,Payment For Dec'13 Staff EPF Contribution,301-001,----,...,480.00,NaN,NaN,171,F,NaN,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17801,78807,OR 220524,OR,2022-05-24,2022-05-24,2022-05-24,SHENZHEN STS MICROELECTRONICS CO LTD,Payment For Invoice - IN2201-021,301-003,CN,...,28277.80,PM,NaN,39129,F,NaN,NaN,0,NaN,NaN
17802,78809,OR 220525,OR,2022-05-26,2022-05-26,2022-05-26,PALMTOP VEGEOIL PRODUCTS SDN BHD,Payment For Invoice - IN2204-037,301-003,JB,...,295.00,PM,NaN,39167,F,NaN,NaN,0,NaN,NaN
17803,78811,OR 220526,OR,2022-05-27,2022-05-27,2022-05-27,FGV JOHOR BULKERS SDN BHD,Payment For Invoice - IN2204-124,301-003,JB,...,1060.00,PM,NaN,39196,F,NaN,NaN,0,NaN,NaN
17804,78813,OR 220527,OR,2022-05-27,2022-05-27,2022-05-27,ANALOG DEVICES SDN.BHD,Payment For Invoice - IN2204-052,301-003,----,...,2250.00,PM,NaN,39197,F,NaN,NaN,0,NaN,NaN
17805,78815,OR 220528,OR,2022-05-27,2022-05-27,2022-05-27,ON SEMICONDUCTOR MALAYSIA SDN.BHD,"Payment For Invoice - IN2203-008, IN2203-009, ...",301-003,SEREMBAN,...,14550.72,PM,NaN,39198,F,NaN,NaN,0,NaN,NaN

In [3]:
cash_book_column = cash_book.columns
print(cash_book_column)

Index(['DOCKEY', 'DOCNO', 'DOCTYPE', 'DOCDATE', 'POSTDATE', 'TAXDATE',
       'DESCRIPTION', 'DESCRIPTION2', 'PAYMENTMETHOD', 'AREA', 'AGENT',
       'PROJECT', 'JOURNAL', 'CHEQUENUMBER', 'CURRENCYCODE', 'CURRENCYRATE',
       'BANKCHARGE', 'BANKCHARGEACCOUNT', 'DOCAMT', 'LOCALDOCAMT',
       'FROMDOCTYPE', 'BOUNCEDDATE', 'GLTRANSID', 'CANCELLED', 'DEPOSITKEY',
       'UPDATECOUNT', 'PRINTCOUNT', 'ATTACHMENTS', 'NOTE'],
      dtype='object')

In [1]:
cash_book = cash_book.drop(['DOCNO', 'DOCDATE', 'POSTDATE', 'TAXDATE', 'DESCRIPTION', 'DESCRIPTION2', 'AREA', 'AGENT', 'PROJECT', 'CURRENCYCODE', 'CURRENCYRATE', 'DOCAMT', 'FROMDOCTYPE', 'BOUNCEDDATE', 'GLTRANSID', 'CANCELLED', 'DEPOSITKEY', 'UPDATECOUNT', 'PRINTCOUNT', 'ATTACHMENTS', 'NOTE'], axis=1)
cash_book

NameError: name 'cash_book' is not defined

In [5]:
# Drop rows with missing values in the target variable
cash_book = cash_book.dropna(subset=['BANKCHARGE'])
cash_book = cash_book.dropna(subset=['BANKCHARGEACCOUNT'])
cash_book = cash_book[cash_book['DOCTYPE'] != 'PV']
cash_book

,DOCKEY,DOCTYPE,PAYMENTMETHOD,JOURNAL,CHEQUENUMBER,BANKCHARGE,BANKCHARGEACCOUNT,LOCALDOCAMT
31,392,OR,301-001,BANK,IMEP-465778,1.00,703-000,5350.0
43,417,OR,301-001,BANK,IMEP-471454,1.00,703-000,8880.0
45,421,OR,301-001,BANK,IMEP-472560,1.00,703-000,2000.0
46,425,OR,301-001,BANK,IMEP-490082,1.00,703-000,4940.0
47,427,OR,301-001,BANK,IMEP-493802,1.00,703-000,32500.0
...,...,...,...,...,...,...,...,...
17573,77741,OR,301-007,BANK,YIR204290865,26.17,703-000,56357.8
17585,77765,OR,301-003,BANK,IBG ONLINE,0.10,703-000,1500.0
17586,77768,OR,301-003,BANK,TXB220428052512,102.21,703-000,78250.0
17658,78089,OR,301-007,BANK,YIR205130185,29.00,703-000,9669.0
17801,78807,OR,301-003,BANK,6181852140FS,128.58,703-000,28277.8

In [6]:
# Use OneHotEncoder instead of LabelEncoder for categorical features
onehot_encoder = OneHotEncoder(sparse=False, drop='first')

In [7]:
# Transform 'PAYMENTMETHOD' using one-hot encoding
payment_method_encoded = onehot_encoder.fit_transform(cash_book[['PAYMENTMETHOD']])
payment_method_columns = onehot_encoder.get_feature_names_out(['PAYMENTMETHOD'])

C:\Users\SQL\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [8]:
# Combine the one-hot encoded features with the other numerical feature
features = pd.concat([cash_book[['LOCALDOCAMT']], pd.DataFrame(payment_method_encoded, columns=payment_method_columns)], axis=1)
target = cash_book['BANKCHARGE']

In [9]:
# Drop any remaining rows with missing values from both features and target
features_target_combined = pd.concat([features, target], axis=1).dropna()
features = features_target_combined.iloc[:, :-1]
target = features_target_combined.iloc[:, -1]

In [10]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.1, random_state=10)
X_train

,LOCALDOCAMT,PAYMENTMETHOD_301-003,PAYMENTMETHOD_301-004,PAYMENTMETHOD_301-006,PAYMENTMETHOD_301-007,PAYMENTMETHOD_301-009,PAYMENTMETHOD_301-010,PAYMENTMETHOD_303-000
45,2000.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
46,4940.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
147,5804.56,0.0,0.0,0.0,0.0,0.0,1.0,0.0
139,1404.50,0.0,0.0,1.0,0.0,0.0,0.0,0.0
417,5827.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0
138,2100.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0
43,8880.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145,2226.00,0.0,0.0,0.0,0.0,1.0,0.0,0.0
140,35549.43,1.0,0.0,0.0,0.0,0.0,0.0,0.0
144,20352.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0
49,4940.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0
137,14576.06,0.0,0.0,1.0,0.0,0.0,0.0,0.0
405,3200.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0
411,4500.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
418,19000.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
404,6470.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
136,1000.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0
416,2100.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0
419,14984.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0
51,5968.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
412,2100.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
142,6708.74,0.0,0.0,1.0,0.0,0.0,0.0,0.0
143,450.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0
31,5350.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
141,477.00,0.0,0.0,0.0,0.0,0.0,1.0,0.0
47,32500.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
52,2200.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [11]:
# Initialize and train the RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [12]:
# Make predictions on the test set
predictions = model.predict(X_test)

In [13]:
# Evaluate the model
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, predictions)

In [14]:
print(f'Mean Squared Error (MSE): {mse}')
print(f'Root Mean Squared Error (RMSE): {rmse}')
print(f'R-squared (R2): {r2}')

Mean Squared Error (MSE): 3.2399999999975096e-06
Root Mean Squared Error (RMSE): 0.0017999999999993082
R-squared (R2): 0.9959500000000031

In [15]:
# Now you can use the trained model to make predictions for new data
new_data = pd.DataFrame({'PAYMENTMETHOD': ['301-001'],
                         'LOCALDOCAMT': [5350]})
new_data_encoded = pd.DataFrame(onehot_encoder.transform(new_data[['PAYMENTMETHOD']]), columns=payment_method_columns)
new_data = pd.concat([new_data[['LOCALDOCAMT']], new_data_encoded], axis=1)

# Ensure new_data has all the necessary columns with zero values
missing_columns = set(X_train.columns) - set(new_data.columns)
for col in missing_columns:
    new_data[col] = 0

# Reorder columns to match the order during training
new_data = new_data[X_train.columns]

prediction_new_data = model.predict(new_data)

print(f'Predicted BANKCHARGE for new data: {prediction_new_data[0]}')

Predicted BANKCHARGE for new data: 1.0024000000000002