In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('C:/Users/Dan/categorized_expenses_desc.csv')

In [5]:
df

,Unnamed: 0,CODE,GL_DESCRIPTION,CB_DESCRIPTION,FORMAT,Who,What,Why,Where,When
0,0,903-000,ENTERTAINMENT,- WREATH,What,NaN,WREATH,NaN,NaN,NaN
1,1,903-000,ENTERTAINMENT,- FRIM & COWAY AUDIT LUNCH,Who-What,FRIM & COWAY,AUDIT LUNCH,NaN,NaN,NaN
2,2,903-000,ENTERTAINMENT,- COWAY LUNCH,What,NaN,COWAY LUNCH,NaN,NaN,NaN
3,3,903-000,ENTERTAINMENT,- COWAY LUNCH,What,NaN,COWAY LUNCH,NaN,NaN,NaN
4,4,903-000,ENTERTAINMENT,- COWAY,What,NaN,COWAY,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2072,2072,968-000,HRDF EXPENSES,BEING CLAIM FOR 5S GOOD HOUSEKEPING PRACTICES ...,What-When,NaN,5S Good Housekeeping Practices,NaN,NaN,16.01.2023
2073,2073,968-000,HRDF EXPENSES,"HRDF FOR THE MONTH OF MAY'23 - RM 480,758.39 @ 1%",What-When,NaN,HRDF,NaN,NaN,May'23
2074,2074,968-000,HRDF EXPENSES,BEING CLAIM FOR TRAINING CERTIFIED HUMAN RESOU...,What-When,NaN,Training Certified Human Resource Manager,NaN,NaN,08.05-12.05.2023
2075,2075,968-000,HRDF EXPENSES,BEING CLAIM FOR TRAINING STOCK AND WAREHOUSE M...,What-When,NaN,Training Stock and Warehouse Management,NaN,NaN,21.12.22-22.12.22
2076,2076,989-000,LOSS IN COURTS CASE,BEING PAYMENT FOR LOSS IN COURTS CASE,What-Why,NaN,PAYMENT,LOSS IN COURTS CASE,NaN,NaN

In [16]:
def find_matching_row(dataframe, **kwargs):
    print(kwargs)
    for index, row in dataframe.iterrows():
        match = all(kwargs[key] == str(row[key]) for key in kwargs)
        if match:
            return row

    return None

# Example usage
user_input_who = input("Enter Who: ")
user_input_what = input("Enter What: ")
user_input_why = input("Enter Why: ")
user_input_where = input("Enter Where: ")
user_input_when = input("Enter When: ")
matching_row = find_matching_row(df, Who=user_input_who, What=user_input_what)

if matching_row is not None:
    print("Matching row found:")
    print(matching_row)
else:
    print("No matching row found.")

Enter Who: FRIM & COWAY
Enter What: AUDIT LUNCH
Enter Why:
Enter Where:
Enter When:
{'Who': 'FRIM & COWAY', 'What': 'AUDIT LUNCH'}
Matching row found:
Unnamed: 0                                  1
CODE                                  903-000
GL_DESCRIPTION                  ENTERTAINMENT
CB_DESCRIPTION     - FRIM & COWAY AUDIT LUNCH
FORMAT                               Who-What
Who                              FRIM & COWAY
What                              AUDIT LUNCH
Why                                       NaN
Where                                     NaN
When                                      NaN
Name: 1, dtype: object